### PR TITLE
Added LazyLoadEncoder, added SebModel and removed EmbeddingModel

### PR DESCRIPTION
**Pull request by x-tabdeveloping**
Implemented changes discussed in #99 
`SebModel` is no longer an `Encoder` but has an `encoder` attribute, that may or may not be a  `LazyLoadEncoder`.
Tests passing.
Also fixed circular imports.

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
Looks good. 

- This is one of the cases I would love to have the static type checks pass (as it is a big overwrite and it check that no cases missed)
- Documentation should also pass. 

Otherwise this looks good.

**Review by KennethEnevoldsen — CHANGES_REQUESTED** [review]
see above

**Comment by x-tabdeveloping** [comment]
All is passing, also fixed some minor errors that our tests did not catch.

**Comment by KennethEnevoldsen** [comment]
Wonderful!

**Pull request merged**
