### PR TITLE
fix: Added new and more comprehensive CLI

### LINKED ISSUE #42: mistral e5  model does not work (or is too slow)
The mistral e5  model does not work (or is too slow) to be applied. The model as added in #40 

@x-tabdeveloping I see that you have implemented it using sentence transformers, but the model [description](https://huggingface.co/intfloat/e5-mistral-7b-instruct) does not use a sentence transformer. Have you tested it out?

### LINKED ISSUE #49: Add ignore cache to CLI

### LINKED ISSUE #55: Add documentation of CLI

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
Including documentation and tests of the CLI

Fixes #55
Fixes #49 
Fixes #42

### CODE REVIEW

**Review by x-tabdeveloping — APPROVED** [review]
Looks good. The only thing I'm missing here is any sort of pretty printing or something along those lines. Of course this can go in an issue.

**Comment by KennethEnevoldsen** [comment]
Yea I was thinking of adding it to a new PR.

**Comment by x-tabdeveloping** [comment]
Tests are failing, do we know why?

**Comment by KennethEnevoldsen** [comment]
Fixing it. It is an odd case. where tests interact due to the registries.

**Pull request merged**
